name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get the latest tag
      id: get-latest-tag
      run: |
        git fetch --tags
        TAG=$(git tag --sort=-v:refname | head -n 1)
        if [ -z "$TAG" ]; then
          echo "tag=0.0.0" >> $GITHUB_ENV
        else
          echo "tag=$TAG" >> $GITHUB_ENV
        fi

    - name: Increment the tag
      id: increment-tag
      run: |
        IFS='.' read -r -a parts <<< "$tag"
        major=${parts[0]}
        minor=${parts[1]}
        patch=${parts[2]}
        patch=$((patch + 1))
        new_tag="$major.$minor.$patch"
        echo "new_tag=$new_tag" >> $GITHUB_ENV

    - name: Create and push new tag
      run: |
        git tag $new_tag
        git push origin $new_tag

    - name: Build and push Docker image
      run: |
        docker buildx build --build-arg APP_VERSION=$new_tag --platform linux/amd64,linux/arm64 -t arsenzvdocker/hometasks-dashboard:$new_tag --push . 
        docker buildx build --build-arg APP_VERSION=$new_tag --platform linux/amd64,linux/arm64 -t arsenzvdocker/hometasks-dashboard:latest --push .
